[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit ADS1X15 @ ^2.5.0

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 10.0.0.7
upload_flags =
  --auth=aquaph1234
  --timeout=60
